### ISSUE TITLE
support arm64

### ISSUE THREAD

**Issue by johnB96** [cloudposse/terraform-aws-ecs-web-app#187]
When using the latest release (0.67.1), terraform init fails with the following message on arm64
```
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
```
hashicorp/template seems to only be used in examples and those examples don't use template_file so removing those should be trivial, something similar to https://github.com/sonatype/terraform-aws-ecs-web-app/commit/f0aff0d7702327798b95609fab659c5356351f3a

However, there are some modules that require an upgrade and other issues that need to be fixed first to fully support arm64
- https://github.com/cloudposse/terraform-github-repository-webhooks/issues/34
- https://github.com/cloudposse/terraform-aws-ecs-codepipeline/issues/92

**Comment by jabcoder** [comment]
I think this is still an issue.

**Comment by nitrocode** [comment]
The module version was updated in pr https://github.com/cloudposse/terraform-aws-ecs-web-app/pull/174
