### ISSUE TITLE
Is it possible to configure optional cloudwatch config fields?

### ISSUE THREAD

**Issue by EthanYe0630** [cloudposse/terraform-aws-ecs-web-app#192]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## I'd like to configure "awslogs-multiline-pattern" through terraform, however, it seems not possible, I'm able to change 'region' and logdriver but not the optional fields https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html

Is it supported? is there a plan to support this? is there a workaround?

**Comment by nitrocode** [comment]
You could override the container definition using `var.container_definition`
