### ISSUE TITLE
ECR is always creating despite codepipeline=false

### ISSUE THREAD

**Issue by rfvermut** [cloudposse/terraform-aws-ecs-web-app#27]
Should add `enabled = ${var.codepipeline_enabled}` if module supports it.
https://github.com/cloudposse/terraform-aws-ecs-web-app/blob/master/main.tf#L9

Because variable is documented as "A boolean to enable/disable AWS Codepipeline and ECR"

**Comment by aknysh** [comment]
agree @rfvermut 
will you be able to open a PR?
thanks

**Comment by rfvermut** [comment]
Totally. Especially if you would consider my job application :)

**Comment by aknysh** [comment]
:)

@osterman  ^

**Comment by aknysh** [comment]
https://cloudposse.com/jobs/

**Comment by rfvermut** [comment]
![image](https://user-images.githubusercontent.com/13441442/55990585-b1e3b300-5cb0-11e9-84ae-cf5e5c5cc240.png)
