### ISSUE TITLE
Allow overriding the container_definition

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-aws-ecs-web-app#57]
Allow overriding the container_definition and disable cloudwatch log creation.

My use case is that I want to pass in a list of container definitions and not log to cloudwatch. We can append the list of container definitions using `var.init_containers` but unfortunately cannot overrride.

It would be nice if there was a `var.override_container_definition` and it simply stops cloudwatch creation and uses the `var.init_containers` as the list of definitions.

**Comment by jamengual** [comment]
we are happy to receive PRs :)

**Comment by nitrocode** [comment]
These issues are written so i can put in a pr
