### ISSUE TITLE
Use Terraform registry instead of Github in modules sources

### ISSUE THREAD

**Issue by mhmdio** [cloudposse/terraform-aws-ecs-web-app#74]
## Describe the Feature

Use Terraform registry in all examples, instead of Github in modules sources, this gives consistency between all the modules, and make it easy to upgrade or downgrade a specific module.

## Expected Behavior

```hcl
module "ecs-web-app" {
  source  = "cloudposse/ecs-web-app/aws"
  version = "0.44.0"
  # insert the 21 required variables here
}
```

**Comment by nitrocode** [comment]
The version can be updated and downgraded using the git method by changing the tag in the source. We use this method across all the different modules in this org.
