### ISSUE TITLE
ECR outside of web-app ?

### ISSUE THREAD

**Issue by maartenvanderhoef** [cloudposse/terraform-aws-ecs-web-app#8]
Hi Sarkis, I find having ECR inside the webapp complicated for two reasons.

1. In many cases you see web-worker patterns. WEB application is handling incoming requests, pushes info to sqs, redis, what not. Worker takes care of handling them. In most cases this is the same Docker but two different ecs services. Having the ECR Repo decoupled from the webapp allows that.

2. With big terraform changes, major version module updates, it's sometime easier, to just delete the webapp, and apply again. Especially when Terraform is not handling changes so well around ecs_service and alb_handling. Having ECR inside your webapp makes this tricky and near impossible.

**Comment by sarkis** [comment]
Good call on this - taking a look to see if it makes sense to decouple

**Comment by osterman** [comment]
@maartenvanderhoef great feedback and arguments. It's a strong case we should consider. Your most compelling argument is (1), but I'm sympathetic to (2) and losing the past images.

I am thinking we might need to create different flavors of this module.

**Comment by nitrocode** [comment]
The ECR creation can be disabled by setting `codepipeline_enabled = false` which prevents the installation of ECR. However, it also prevents the ability of using the codepipeline. 

Is this ticket still relevant?
